### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by tonyhogben** [flore2003/nativescript-markdown-view#12]
I have implemented as per the demo and all is working fine on Android but there is no formatting applied in iOS.

### Which platform(s) does your issue occur on?
- iOS
- 
- emulator (all) and device (iPhone X)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: 6.3.2
- iOS Runtime: 6.3.0
- Plugin(s): 
  "dependencies": {
    "@nativescript/theme": "~2.2.1",
    "nativescript-markdown-view": "1.4.1",
    "tns-core-modules": "~6.3.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.4.0",
    "node-sass": "^4.7.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Just follow the demo instructions

**Comment by flore2003** [comment]
Can you let me know which version of iOS you have tested this on?

**Comment by tonyhogben** [comment]
13.3.1

**Comment by flore2003** [comment]
Version 2.0.0 was just released, can you check if this solves your issue? I can't reproduce the formatting not being shown.

**Comment by shiv19** [comment]
I got this error log on iOS @flore2003 
```
CONSOLE ERROR file:///app/bundle.js:1407:20: Error Domain=file:///app/vendor.js@114391:74 Code=-6661 "(null)" UserInfo={sourceURL=file:///app/vendor.js, line=114391, msg=Error: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1], nativeException=*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1], stackTrace=JS:
dictionaryWithObjectsForKeys(file: node_modules/nativescript-markdown-view/markdown-view.ios.js:41:0)
at file: node_modules/nativescript-markdown-view/markdown-view.ios.js:41:0
at file: node_modules/nativescript-markdown-view/markdown-view.ios.js:22:0
at applyAllNativeSetters(file: node_modules/@nativescript/core/ui/core/properties/properties.js:1065:0)
at initNativeView(file: node_modules/@nativescript/core/ui/core/properties/properties.js:992:0)
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:647:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:278:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0
at file: node_modules/@nativescript/core/ui/text-view/text-view.ios.js:119:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at fil<\M-b\M^@\M-&>
```
"nativescript-markdown-view": "2.0.0",

**Comment by tonyhogben** [comment]
Sorry for the delay @flore2003, all working!
