### ISSUE TITLE
NS 7 support

### ISSUE THREAD

**Issue by eloiqs** [flore2003/nativescript-markdown-view#18]
Hey there 👋 

Does this library already support NS 7? When looking at the source code I notice some @nativescript/core imports but the package.json version seems to be 6.x.x. 

If it isn't yet supported, are there any plans to update the library?

Thank you.

**Comment by flore2003** [comment]
I don't currently work with NS at all, thus it will be hard for me to do the upgrade any time soon, but you are more than welcome to submit a PR.

**Comment by flore2003** [comment]
This should be closed by #20
